FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY *.go .

RUN CGO_ENABLED=0 GOOS=linux go build -o /go-example

FROM alpine:latest

COPY --from=builder /go-example /go-example

CMD ["/go-example"]

